jailer:Check cgroup name for path traversal tokens
firecracker-microvm/firecracker pull request #2869
Opened 2022-01-18 14:58 UTC by AlexandruCihodaru

Signed-off-by: AlexandruCihodaru <cihodar@amazon.com>
Suggested-by: Alexandru-Cezar Sardan <alsardan@amazon.com>

# Reason for This PR

`[Author TODO: add issue #.]`
`[Open the PR after the related issue has a clear conclusion.]`
`[If there is no issue which states the need for this PR, create one first.]`
Fixes #

## Description of Changes

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The issue which led to this PR has a clear conclusion.
- [x] This PR follows the solution outlined in the related issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any newly added `unsafe` code is properly documented.
- [x] Any API changes follow the [Runbook for Firecracker API changes][2].
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

2022-01-18 15:31 UTC, alsrdn requested changes

2022-01-18 15:31 UTC, alsrdn commented on src/jailer/src/env.rs
> +            cgroups: vec!["./root/", "../root"],
It's maybe best if we have 2 tests here: one for when the path contains ./ or ../ and another for when the cgroup is specified in the wrong format (not in cgroup_file=value format). With this test we can get an error either if the parameter contains current/parent dir or if it does not have the proper format.

2022-01-18 17:02 UTC, alsrdn approved these changes

2022-01-19 10:09 UTC, alindima approved these changes

2022-01-19 10:12 UTC, alsrdn approved these changes

2022-01-19 10:12 UTC, merged