Added functionality to change mount directory in build_rootfs command
firecracker-microvm/firecracker pull request #3086
Opened 2022-08-09 00:03 UTC by sondavidb

Signed-off-by: David Son <davbson@amazon.com>

# Reason for This PR

Fixes #3058

## Description of Changes

`[Author TODO: add description of changes.]`

- [ ] This functionality can be added in [`rust-vmm`][1].

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [X] All commits in this PR are signed (`git commit -s`).
- [X] The issue which led to this PR has a clear conclusion.
- [X] This PR follows the solution outlined in the related issue.
- [X] The description of changes is clear and encompassing.
- [X] Any required documentation changes (code and docs) are included in this PR.
- [X] Any newly added `unsafe` code is properly documented.
- [X] Any API changes follow the [Runbook for Firecracker API changes][2].
- [X] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [X] All added/changed functionality is tested.

[1]: https://github.com/rust-vmm
[2]: ../docs/api-change-runbook.md

2022-08-09 06:07 UTC, luminitavoicu commented on tools/devtool
>  img_file="$rootfs_dir/$ROOTFS_NAME"
I don't see the need for an additional local variable here, you could just use `$ROOTFS_DIR`:

```suggestion
img_file="$ROOTFS_DIR/$ROOTFS_NAME"
```

2022-08-10 05:33 UTC, luminitavoicu approved these changes

2022-08-10 06:02 UTC, luminitavoicu requested changes
Changes look good! Please make sure your commit message obeys the 50/72 rule (see the CI style error).

2022-08-11 20:47 UTC, sondavidb commented
@luminitavoicu Changed and also made the PR message slightly more verbose

2022-08-12 08:51 UTC, luminitavoicu approved these changes

2022-08-16 14:17 UTC, dianpopa approved these changes

2022-08-16 14:17 UTC, merged