Docs: Update snapshot support doc.
firecracker-microvm/firecracker pull request #3214
Opened 2022-10-27 12:38 UTC by vibharya

- Add details to the snapshot characteristics
- Fix vsock limitation link within doc
- Remove one of two known issues link.

Signed-off-by: Vibha Acharya <vibharya@amazon.co.uk>

## Changes

...

## Reason

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] New `unsafe` code is documented.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

2022-10-27 13:12 UTC, pb8o requested changes

2022-10-27 13:12 UTC, pb8o commented on docs/snapshotting/snapshot-support.md
> +  store is notpersisted across snapshots.
typo: not persisted

2022-10-27 13:12 UTC, pb8o commented on docs/snapshotting/snapshot-support.md
> +- The Firecracker micoVM's MMDS config is included in the snapshot. However, the data
typo: micoVM

2022-10-27 15:57 UTC, dianpopa approved these changes

2022-10-28 13:42 UTC, pb8o approved these changes

2022-10-31 09:13 UTC, pb8o approved these changes

2022-11-01 10:15 UTC, dianpopa approved these changes

2022-11-01 10:16 UTC, merged