Changelog updated.
firecracker-microvm/firecracker pull request #3289
Opened 2022-11-24 10:54 UTC by andreitraistaru

Signed-off-by: Trăistaru Andrei Cristian <atc@amazon.com>

## Reason

Keep track of Rust toolchain upgrade in CHANGELOG.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

## PR Checklist

- [ ] All commits in this PR are signed (`git commit -s`).
- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] New `unsafe` code is documented.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [ ] All added/changed functionality is tested.

---

- [ ] This functionality can be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md

2022-11-24 10:55 UTC, zulinx86 approved these changes

2022-11-24 11:51 UTC, zulinx86 reviewed
Could you mention the commit that upgraded it to 1.64.0 in this PR or the commit message?

2022-11-24 12:04 UTC, zulinx86 approved these changes

2022-11-24 18:45 UTC, xmarcalx requested changes

2022-11-24 18:45 UTC, xmarcalx commented on CHANGELOG.md
> +- Rust toolchain upgraded to 1.64.0.
let's add also: from x to y

2022-11-25 08:57 UTC, zulinx86 approved these changes

2022-11-25 09:04 UTC, xmarcalx commented on CHANGELOG.md
> +- Rust toolchain upgraded to 1.64.0.
thanks a lot!

2022-11-25 09:04 UTC, xmarcalx approved these changes
LGTM, thanks a lot

2022-11-25 10:17 UTC, merged