fix: Move `arch_gen` into module under `vmm`
firecracker-microvm/firecracker pull request #3528
Opened 2023-03-14 15:40 UTC by JonathanWoollett-Light

## Changes

Moved `arch_gen` into module under `vmm`.

## Reason

See https://github.com/firecracker-microvm/firecracker/pull/3079

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2023-03-24 07:31 UTC, JonathanWoollett-Light commented
Blocked on merging of either https://github.com/firecracker-microvm/firecracker/pull/3530 or https://github.com/firecracker-microvm/firecracker/pull/3534.

2023-03-28 17:06 UTC, zulinx86 requested changes
You might want to update [`tools/bindgen.sh`](https://github.com/firecracker-microvm/firecracker/blob/main/tools/bindgen.sh) so that it outputs into `src/vmm/src/arch_gen/`.

2023-03-28 17:45 UTC, JonathanWoollett-Light commented
> You might want to update [`tools/bindgen.sh`](https://github.com/firecracker-microvm/firecracker/blob/main/tools/bindgen.sh) so that it outputs into `src/vmm/src/arch_gen/`.

Fixed.

2023-03-29 15:13 UTC, zulinx86 approved these changes

2023-03-29 15:30 UTC, merged