Todo
firecracker-microvm/firecracker pull request #3636
Opened 2023-04-26 23:10 UTC by StonewallJohnson

## Changes

- Added doc string to Endpoint::new()
- Found better name for app_metrics

## Reason

Resolve TODOs according to #3273

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- &#9745; If a specific issue led to this PR, this PR closes the issue.
- &#9745; The description of changes is clear and encompassing.
- &#9745; Any required documentation changes (code and docs) are included in this PR.
- &#9745; API changes follow the [Runbook for Firecracker API changes][2].
- &#9745; User-facing changes are mentioned in `CHANGELOG.md`.
- &#9745; All added/changed functionality is tested.
- &#9745; New `TODO`s link to an issue.
- &#9745; Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2023-05-30 09:51 UTC, roypat requested changes

2023-05-30 09:51 UTC, roypat commented on .github/pull_request_template.md
Mhh, it looks like you put the pull request description into the template file, instead of just filing it out on GitHub :thinking: Could you drop this file from your PR, please?

2023-05-30 09:51 UTC, roypat commented on src/logger/src/metrics.rs
> +    pub metrics_buf_input: T,
Mhh, the only reason this name makes sense is because of the todo-comment, which this PR removes. Maybe `metrics_data` makes more sense?

2023-05-30 09:51 UTC, roypat commented on src/dumbo/src/tcp/endpoint.rs
> +    /// Asserts that RCV_BUF_MAX_SIZE <= MAX_WINDOW_SIZE
Could we instead write a complete doc comment here with a `## Panics:` section that mentions this simplifying assumption?

2023-08-07 10:05 UTC, xmarcalx commented
Hi @StonewallJohnson ,

Thanks for your contribution.
Are you still following this PR? Can you address @roypat comments?

2024-05-14 09:47 UTC, closed without merging