ci: Test for unused dependencies
firecracker-microvm/firecracker pull request #4117
Opened 2023-09-20 13:56 UTC by JonathanWoollett-Light

## Changes

Adds a test for unused cargo dependencies.

## Reason

Prevents including unused dependencies see https://github.com/firecracker-microvm/firecracker/pull/4113#discussion_r1331364257

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] API changes follow the [Runbook for Firecracker API changes][2].
- [x] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [x] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2023-09-20 14:49 UTC, JonathanWoollett-Light commented
Blocked on docker changes from: https://github.com/firecracker-microvm/firecracker/pull/4089

2023-09-25 08:59 UTC, roypat commented
Unblocked :)

2023-09-25 09:02 UTC, JonathanWoollett-Light commented
https://github.com/firecracker-microvm/firecracker/pull/4089 merged, unblocked.

2023-10-03 16:37 UTC, roypat approved these changes

2023-10-03 16:48 UTC, bchalios requested changes
Could you please break this down to two commits, one that adds the test (test, Docker changes) and one that removes the unused dependencies?

Also, there are here, seemingly, completely unrelated changes (the ones in the documentation). Please drop these and add them in a different PR.

2023-10-04 10:35 UTC, JonathanWoollett-Light commented
> Could you please break this down to two commits, one that adds the test (test, Docker changes) and one that removes the unused dependencies?

I've updated the PR breaking it down into 4 commits.

> Also, there are here, seemingly, completely unrelated changes (the ones in the documentation). Please drop these and add them in a different PR.

These are required by the updated version of markdown lint. `mdl` is a ruby dependency so we don't have a lock file for it.

2023-10-04 10:39 UTC, roypat submitted a review, later dismissed

2024-12-11 16:26 UTC, pb8o approved these changes

2024-12-11 16:26 UTC, pb8o commented on tests/integration_tests/build/test_dependencies.py
> +# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
2024 :)

2024-12-11 16:28 UTC, roypat commented on tests/integration_tests/build/test_dependencies.py
> +# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
LOL

fixed

2024-12-11 16:28 UTC, roypat submitted a review, later dismissed

2024-12-11 16:51 UTC, roypat approved these changes

2024-12-16 10:22 UTC, merged