[1.5] Backport firecracker#4353 to fix cargo audit
firecracker-microvm/firecracker pull request #4365
Opened 2024-01-15 15:00 UTC by sudanl0

bump rust dependencies by backporting
https://github.com/firecracker-microvm/firecracker/pull/4353 to fix cargo audit warnings.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following
Developer Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [ ] If a specific issue led to this PR, this PR closes the issue.
- [x] The description of changes is clear and encompassing.
- [ ] Any required documentation changes (code and docs) are included in this PR.
- [ ] API changes follow the [Runbook for Firecracker API changes][2].
- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.
- [ ] New `TODO`s link to an issue.
- [x] Commits meet [contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-standards).

---

- [x] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2024-01-15 15:08 UTC, pb8o reviewed
Just curious: any reason why we didn't use `git cherry-pick -x` here?

2024-01-15 15:33 UTC, sudanl0 commented
> Just curious: any reason why we didn't use `git cherry-pick -x` here?

I found it easier to pick changes manually than resolving the conflicts from cherry-picking the commit from the main branch

2024-01-17 10:44 UTC, pb8o submitted a review, later dismissed

2024-01-17 16:42 UTC, bchalios requested changes

2024-01-17 16:42 UTC, bchalios commented on tests/integration_tests/functional/test_shut_down.py
> +            if "6.1" in platform.release()
same as with 1.6 backport. We should cherry-pick this one: 91188f36a1e517beb0429a0f4811228e256dc814 as well

2024-01-18 09:40 UTC, bchalios approved these changes

2024-01-18 09:44 UTC, merged