fix: rename page_size_kib to page_size
firecracker-microvm/firecracker pull request #4948
Opened 2024-12-06 13:09 UTC by acsmyth

## Changes
* 
...

## Reason

...

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] I have read and understand [CONTRIBUTING.md][3].
- [x] I have run `tools/devtool checkstyle` to verify that the PR passes the
  automated style checks.
- [x] I have described what is done in these changes, why they are needed, and
  how they are solving the problem in a clear and encompassing way.
- [ ] I have updated any relevant documentation (both in code and in the docs)
  in the PR.
- [ ] I have mentioned all user-facing changes in `CHANGELOG.md`.
- [ ] If a specific issue led to this PR, this PR closes the issue.
- [ ] When making API changes, I have followed the
  [Runbook for Firecracker API changes][2].
- [ ] I have tested all new and changed functionalities in unit tests and/or
  integration tests.
- [ ] I have linked an issue to every new `TODO`.

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2024-12-09 12:38 UTC, pb8o requested changes

2024-12-09 12:38 UTC, pb8o commented on tests/integration_tests/performance/test_huge_pages.py
> +    assert kernel_page_size > 4096
Is this intended? the `smaps` file does report this value in kB:

```
KernelPageSize:        4 kB
```

I think this should be left as-is.

2024-12-10 09:26 UTC, pb8o commented on tests/integration_tests/performance/test_huge_pages.py
> +    assert kernel_page_size > 4096
Other than that, it looks good to me. Thanks for your contribution! :)

2024-12-13 12:55 UTC, roypat commented
Hi @acsmyth, 
thanks for catching this! The team's discussed this, and we agreed that although huge pages support is somewhat new, this would still be a breaking change, and so there should be some sort of transition period for users of Firecracker. So for that reason, I think we should just carry two fields for a while (e.g. both `page_size` and `page_size_kib` with the broken semantics). That being said, I think most of your PR can go through unchanged, we'll only need to readd `page_size_kib` to `GuestRegionUffdMapping` and set it to the same value as `page_size` in `create_guest_memory`. We'd also need to add something to `DEPRECATED.md` warning that we'll remove `page_size_kib` in an upcoming version.

2025-03-17 15:22 UTC, pb8o approved these changes

2025-03-17 15:29 UTC, pb8o approved these changes

2025-03-19 15:26 UTC, merged