tests: parametrize bench mark tests
firecracker-microvm/firecracker pull request #4974
Opened 2024-12-30 06:43 UTC by cm-iwata

In the previous implementation, it was necessary to adjust the timeout value every time a benchmark test added.
By parametrizing the benchmark tests, the time required for each test becomes predictable, eliminating the need to adjust the timeout value

## Changes

Parametrize the test by the list of criterion benchmarks 

## Reason

close #4832

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license. For more information on following Developer
Certificate of Origin and signing off your commits, please check
[`CONTRIBUTING.md`][3].

## PR Checklist

- [x] I have read and understand [CONTRIBUTING.md][3].
- [x] I have run `tools/devtool checkstyle` to verify that the PR passes the
  automated style checks.
- [x] I have described what is done in these changes, why they are needed, and
  how they are solving the problem in a clear and encompassing way.
- [ ] I have updated any relevant documentation (both in code and in the docs)
  in the PR.
- [ ] I have mentioned all user-facing changes in `CHANGELOG.md`.
- [x] If a specific issue led to this PR, this PR closes the issue.
- [ ] When making API changes, I have followed the
  [Runbook for Firecracker API changes][2].
- [x] I have tested all new and changed functionalities in unit tests and/or
  integration tests.
- [ ] I have linked an issue to every new `TODO`.

______________________________________________________________________

- [ ] This functionality cannot be added in [`rust-vmm`][1].

[1]: https://github.com/rust-vmm
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.md
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md

2025-01-08 13:51 UTC, pb8o submitted a review, later dismissed

2025-01-08 14:00 UTC, roypat requested changes
I think like this we're no longer doing an A/B-test, we're just benchmarking the same binary compiled from the PR branch twice (e.g. comparing the PR results to themselves)

2025-01-08 14:00 UTC, roypat commented on tests/integration_tests/performance/test_benchmarks.py
> +    )
Mhh, I don't think this does what we want. We precompile the executables ones (from the PR branch), and then we use this precompiled executable for both A and B runs. What need to do though is compile each benchmark twice, ones from the main branch and once from the PR branch, so that this test does a meaningful comparison :/ That's why in #4832 I suggested to use `--list-only` or something: determine the names of the benchmarks here, and then compile them twice in `_run_criterion`

2025-01-12 08:51 UTC, cm-iwata commented on tests/integration_tests/performance/test_benchmarks.py
> +@pytest.mark.timeout(600)
fix in 215af23e54aa51859c6a0fcd07e0625615026f84

2025-01-12 08:53 UTC, cm-iwata commented on tests/integration_tests/performance/test_benchmarks.py
> +    for line in stdout.split("\n"):
fix in b95900e0bca410722add733a8bb2370e3080ecbf

And I realized there are mamy same implementation.

https://github.com/search?q=repo%3Afirecracker-microvm%2Ffirecracker%20split(%22%5Cn%22)&type=code

2025-01-12 09:39 UTC, cm-iwata commented on tests/integration_tests/performance/test_benchmarks.py
> +    )
Sorry, I think I misunderstood a bit how it works.

Let me confirm the modifications.
First, run `cargo bench --all -- --list` to generate parameters to pass to `pytest.parametrize`.
I will get the following output:

```
root@90de30508db0:/firecracker# cargo bench --all -- --list Finished `bench` profile [optimized] target(s) in 0.10s Running benches/block_request.rs (build/cargo_target/release/deps/block_request-2e4b90407b22a8d0) request_parse: benchmark Running benches/cpu_templates.rs (build/cargo_target/release/deps/cpu_templates-cd18fd51dbad16f4) Deserialization test - Template size (JSON string): [2380] bytes. Serialization test - Template size: [72] bytes. deserialize_cpu_template: benchmark serialize_cpu_template: benchmark Running benches/memory_access.rs (build/cargo_target/release/deps/memory_access-741f97a7c9c33391)
page_fault: benchmark

page_fault #2: benchmark

Running benches/queue.rs (build/cargo_target/release/deps/queue-b2dfffbab00c4157)
next_descriptor_16: benchmark

queue_pop_16: benchmark

queue_add_used_16: benchmark

queue_add_used_256: benchmark
```

And then, I will get  benchmark name...for example `queue_pop_16`.

Finally run a command like `cargo bench --all -- queue_pop_16` in `_run_criterion`.
Is this correct?

2025-01-16 14:58 UTC, roypat commented on tests/integration_tests/performance/test_benchmarks.py
> +    )
Yes, that's pretty much it! The main point is that the compilation of the benchmarks needs to happen in _run_criterion, because we actually _have_ to compile them twice, once for the pull request target, and once for the pull request head.

2025-04-27 09:29 UTC, cm-iwata commented on tests/integration_tests/performance/test_benchmarks.py
> +@pytest.mark.timeout(600)
When I verified this, I found that the first execution would require more than 300 seconds of overhead, so 300 seconds is too short.

```
root@94c9107981fb:/firecracker/tests# pytest "integration_tests/performance/test_benchmarks.py"  -m no_block_pr --durations=0 -v
================================================================================================== test session starts ===================================================================================================
platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0 -- /opt/venv/bin/python
cachedir: ../build/pytest_cache
metadata: {'Python': '3.12.3', 'Platform': 'Linux-6.8.0-51-generic-x86_64-with-glibc2.39', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.5.0'}, 'Plugins': {'metadata': '3.1.1', 'rerunfailures': '14.0', 'timeout': '2.3.1', 'xdist': '3.6.1', 'json-report': '1.5.0'}}
EC2 AMI: NA
rootdir: /firecracker/tests
configfile: pytest.ini
plugins: metadata-3.1.1, rerunfailures-14.0, timeout-2.3.1, xdist-3.6.1, json-report-1.5.0
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 8 items

integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[serialize_cpu_template] PASSED                                                                      [ 12%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault] PASSED                                                                                  [ 25%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_16] PASSED                                                                           [ 37%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_pop_16] PASSED                                                                                [ 50%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_256] PASSED                                                                          [ 62%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[next_descriptor_16] PASSED                                                                          [ 75%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[request_parse] PASSED                                                                               [ 87%]
integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[deserialize_cpu_template] PASSED                                                                    [100%]

------------------------------------------------------------------------------------------------------ JSON report -------------------------------------------------------------------------------------------------------
report saved to: ../test_results/test-report.json
=================================================================================================== slowest durations ====================================================================================================
315.52s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[serialize_cpu_template]
40.62s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault]
39.61s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_256]
39.57s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[request_parse]
37.05s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_pop_16]
36.06s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[next_descriptor_16]
34.07s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_16]
22.73s call     integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[deserialize_cpu_template]
1.63s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[serialize_cpu_template]
0.15s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[deserialize_cpu_template]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[next_descriptor_16]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_pop_16]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[deserialize_cpu_template]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_256]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_256]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[request_parse]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_16]
0.00s setup    integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_16]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[serialize_cpu_template]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_pop_16]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[next_descriptor_16]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[request_parse]
0.00s teardown integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault]
```

2025-04-28 14:44 UTC, roypat commented
Mh, it would seem that it's still compiling everything multiple times judging by the test runtimes, and that's why its timing out? :thinking:

2025-06-22 13:24 UTC, cm-iwata commented
> Mh, it would seem that it's still compiling everything multiple times judging by the test runtimes, and that's why its timing out? 🤔

@roypat 
Sorry for the late reply.
After investigation, I found that the timeout threshold was too short.
Let's take the following build failure log as an example.

https://buildkite.com/firecracker/firecracker-pr-optional/builds/11752#01967b0d-070f-4a47-ab7c-8aa74ec201ba

This log contains the following log:
```
419.83s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault]
178.50s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_16]
33.90s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_add_used_256]
31.28s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[queue_pop_16]
31.24s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[request_parse]
30.96s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[next_descriptor_16]
24.40s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[deserialize_cpu_template]
20.43s call integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[serialize_cpu_template]
0.17s setup integration_tests/performance/test_benchmarks.py::TestBenchMarks::test_no_regression_relative_to_target_branch[page_fault]
0.09s call integration_tests/functional/test_cpu_template_helper.py::test_guest_cpu_config_change
````

- First, `page_fault` parametrized test is run. Since this is the first test run, a process to build a binary for benchmark tests.
- These processes do not complete within 420 seconds, so the test fails and the binary build is interrupted.
- Next, `queue_add_used_16` is run.
- Since the binary has not yet been built, cargo will build binary, but since there is a build cache generated before the `page_fault` test run, this build completes relatively quickly. Then `queue_add_used_16` completes in 178.5s.
- Next, `queue_add_used_256` is run. Since there is a pre-built binary, this test completes quickly in about 30s. Subsequent tests are similar.

I was able to reproduce the same issue locally, so I increased the timeout threshold.
Could you run CI again?

2025-06-26 09:01 UTC, Manciukic commented
We decided to remove the automated criterion benchmark runs (#5273) as they've been causing more pain with flakiness than they've been useful. So this PR will no longer be relevant

2025-06-26 09:01 UTC, closed without merging